export const ADD_STOPWATCH = 'ADD_STOPWATCH';
export const DELETE_STOPWATCH = 'DELETE_STOPWATCH';
export const SET_STOPWATCH_BEST_TIME = 'SET_STOPWATCH_BEST_TIME';
export const MANUAL_SET_STOPWATCH_BEST_TIME = 'MANUAL_SET_STOPWATCH_BEST_TIME';

export const SET_STOPWATCH_LAPS = 'SET_STOPWATCH_LAPS';
export const DELETE_STOPWATCH_LAPS = 'DELETE_STOPWATCH_LAPS';
export const ADD_STOPWATCH_LAP = 'ADD_STOPWATCH_LAP';
export const CLEAR_STOPWATCH_LAPS = 'CLEAR_STOPWATCH_LAPS';

export const STOPWATCH_START = 'STOPWATCH_START';
export const STOPWATCH_STOP = 'STOPWATCH_STOP';
export const SET_CURRENT_TIME = 'SET_CURRENT_TIME';
